begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select no_plan();
select set_config('test.owner',gen_random_uuid()::text,true);
select set_config('test.other',gen_random_uuid()::text,true);
select set_config('test.tech',gen_random_uuid()::text,true);
insert into auth.users(id) values(current_setting('test.owner')::uuid),(current_setting('test.other')::uuid),(current_setting('test.tech')::uuid);
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
select set_config('test.shop',create_initial_shop('Temporary beta assertions')::text,true);
select set_config('test.feedback',gen_random_uuid()::text,true);
select lives_ok($$insert into beta_feedback(id,shop_id,user_id,path,category,message) values(current_setting('test.feedback')::uuid,current_setting('test.shop')::uuid,auth.uid(),'/customers','bug','Test feedback')$$,'owner submits feedback');
select throws_ok($$insert into beta_feedback(id,shop_id,user_id,path,category,message) values(current_setting('test.feedback')::uuid,current_setting('test.shop')::uuid,auth.uid(),'/customers','bug','Test feedback')$$,'23505',null,'replayed feedback key cannot duplicate');
select throws_ok($$update beta_feedback set message='Replaced feedback'$$,'42501',null,'feedback message is immutable to authenticated clients');
select throws_ok($$delete from beta_feedback$$,'42501',null,'client cannot delete feedback');
select lives_ok($$update beta_feedback set status='reviewed'$$,'owner reviews feedback');
select throws_ok($$insert into beta_feedback(shop_id,user_id,path,category,message,status) values(current_setting('test.shop')::uuid,auth.uid(),'/','bug','Test feedback','resolved')$$,'42501',null,'client cannot choose initial review status');
select set_config('request.jwt.claim.sub',current_setting('test.other'),true);
select create_initial_shop('Temporary other beta shop');
select is((select count(*) from beta_feedback),0::bigint,'other shop cannot read feedback');
select throws_ok($$insert into beta_feedback(shop_id,user_id,path,category,message) values(current_setting('test.shop')::uuid,auth.uid(),'/','bug','Cross shop feedback')$$,'42501',null,'other shop cannot submit feedback');
reset role;
insert into shop_members(shop_id,user_id,role) values(current_setting('test.shop')::uuid,current_setting('test.tech')::uuid,'technician');
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.tech'),true);
select is((select count(*) from beta_feedback),0::bigint,'technician cannot read colleagues feedback');
select lives_ok($$insert into beta_feedback(shop_id,user_id,path,category,message) values(current_setting('test.shop')::uuid,auth.uid(),'/inspections','confusing','Technician feedback')$$,'technician submits own feedback');
select is((select count(*) from beta_feedback),1::bigint,'technician reads own feedback');
update beta_feedback set status='resolved';
select is((select status from beta_feedback),'new','technician cannot review own feedback');
select throws_ok($$insert into beta_feedback(shop_id,user_id,path,category,message) values(current_setting('test.shop')::uuid,current_setting('test.owner')::uuid,'/','bug','Spoofed author')$$,'42501',null,'feedback author must match caller');
set local role anon;
select throws_ok($$select * from beta_feedback$$,'42501',null,'anonymous access denied');
select * from finish();
rollback;
