-- Local fixtures only; all changes roll back, including Storage metadata fixtures.
begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select set_config('test.owner_a',gen_random_uuid()::text,true);
select set_config('test.owner_b',gen_random_uuid()::text,true);
select set_config('test.tech_a',gen_random_uuid()::text,true);
insert into auth.users(id) values(current_setting('test.owner_a')::uuid),(current_setting('test.owner_b')::uuid),(current_setting('test.tech_a')::uuid);
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.owner_a'),true);
select set_config('test.shop_a',create_initial_shop('Phase 6 transaction A')::text,true);
insert into customers(shop_id,first_name,last_name) values(current_setting('test.shop_a')::uuid,'Clinical','A');
select set_config('test.customer_a',(select id::text from customers),true);
insert into vehicles(shop_id,customer_id) values(current_setting('test.shop_a')::uuid,current_setting('test.customer_a')::uuid);
select set_config('test.vehicle_a',(select id::text from vehicles),true);
insert into work_orders(shop_id,customer_id,vehicle_id,status) values(current_setting('test.shop_a')::uuid,current_setting('test.customer_a')::uuid,current_setting('test.vehicle_a')::uuid,'open');
select set_config('test.job_a',(select id::text from work_orders),true);
insert into vehicles(shop_id,customer_id) values(current_setting('test.shop_a')::uuid,current_setting('test.customer_a')::uuid);
select set_config('test.other_vehicle',(select id::text from vehicles where id<>current_setting('test.vehicle_a')::uuid),true);
select set_config('request.jwt.claim.sub',current_setting('test.owner_b'),true);
select set_config('test.shop_b',create_initial_shop('Phase 6 transaction B')::text,true);
select set_config('test.member_b',(select id::text from shop_members),true);
insert into customers(shop_id,first_name,last_name) values(current_setting('test.shop_b')::uuid,'Clinical','B');
select set_config('test.customer_b',(select id::text from customers),true);
insert into vehicles(shop_id,customer_id) values(current_setting('test.shop_b')::uuid,current_setting('test.customer_b')::uuid);
select set_config('test.vehicle_b',(select id::text from vehicles),true);
insert into work_orders(shop_id,customer_id,vehicle_id,status) values(current_setting('test.shop_b')::uuid,current_setting('test.customer_b')::uuid,current_setting('test.vehicle_b')::uuid,'open');
select set_config('test.job_b',(select id::text from work_orders),true);
select set_config('test.inspection_b',create_inspection(current_setting('test.job_b')::uuid,'multipoint','',gen_random_uuid(),current_setting('test.member_b')::uuid)::text,true);
select set_config('test.item_b',(select id::text from inspection_items order by sort_order limit 1),true);
insert into diagnoses(shop_id,work_order_id,vehicle_id,symptoms) values(current_setting('test.shop_b')::uuid,current_setting('test.job_b')::uuid,current_setting('test.vehicle_b')::uuid,'B');
reset role;
insert into shop_members(shop_id,user_id,role) values(current_setting('test.shop_a')::uuid,current_setting('test.tech_a')::uuid,'technician');
select set_config('test.member_a',(select id::text from shop_members where user_id=current_setting('test.tech_a')::uuid),true);
select is((select public from storage.buckets where id='inspection-photos'),false,'photo bucket is private');
select is((select file_size_limit from storage.buckets where id='inspection-photos'),5242880::bigint,'bucket enforces five MB limit');
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.owner_a'),true);
select lives_ok($$insert into diagnoses(shop_id,work_order_id,vehicle_id,technician_id,ai_summary,severity,ai_response) values(current_setting('test.shop_a')::uuid,current_setting('test.job_a')::uuid,current_setting('test.vehicle_a')::uuid,current_setting('test.member_a')::uuid,'Temporary verified test summary','monitor','{"summary":"Temporary verified test summary"}')$$,'owner creates diagnosis');
select is((select count(*) from diagnoses),1::bigint,'owner reads own diagnosis only');
select is((select count(*) from diagnosis_listing),1::bigint,'diagnosis view preserves isolation');
select throws_ok($$insert into diagnoses(shop_id,work_order_id,vehicle_id) values(current_setting('test.shop_b')::uuid,current_setting('test.job_b')::uuid,current_setting('test.vehicle_b')::uuid)$$,'42501',null,'cross-shop diagnosis create denied');
select throws_ok($$insert into diagnoses(shop_id,work_order_id,vehicle_id) values(current_setting('test.shop_a')::uuid,current_setting('test.job_a')::uuid,current_setting('test.other_vehicle')::uuid)$$,'23503',null,'diagnosis vehicle must match job even within same shop');
select throws_ok($$insert into diagnoses(shop_id,work_order_id,vehicle_id,technician_id) values(current_setting('test.shop_a')::uuid,current_setting('test.job_a')::uuid,current_setting('test.vehicle_a')::uuid,current_setting('test.member_b')::uuid)$$,'23503',null,'diagnosis technician belongs to same shop');
select throws_ok($$update diagnoses set shop_id=current_setting('test.shop_b')::uuid$$,'42501',null,'diagnosis tenancy is immutable');
select throws_ok($$update diagnoses set vehicle_id=current_setting('test.other_vehicle')::uuid$$,'42501',null,'diagnosis vehicle context is immutable');
select throws_ok($$delete from diagnoses$$,'42501',null,'diagnosis deletion unavailable');
select set_config('request.jwt.claim.sub',current_setting('test.tech_a'),true);
select lives_ok($$insert into diagnoses(shop_id,work_order_id,vehicle_id,technician_id,symptoms) values(current_setting('test.shop_a')::uuid,current_setting('test.job_a')::uuid,current_setting('test.vehicle_a')::uuid,current_setting('test.member_a')::uuid,'Technician fixture')$$,'technician creates diagnosis');
select lives_ok($$update diagnoses set technician_findings='Observed during test',confirmed_cause='Test only'$$,'technician updates diagnosis');
select is((select count(*) from diagnoses where technician_findings='Observed during test'),2::bigint,'technician findings persist');
select set_config('test.request',gen_random_uuid()::text,true);
select set_config('test.inspection_a',create_inspection(current_setting('test.job_a')::uuid,'pre_inspection','NY',current_setting('test.request')::uuid,current_setting('test.member_a')::uuid)::text,true);
select is((select count(*) from inspections),1::bigint,'technician creates and reads own inspection only');
select is((select count(*) from inspection_listing),1::bigint,'inspection view preserves isolation');
select is((select count(*) from inspection_items),18::bigint,'generic template snapshots all eighteen items');
select is((select count(*) from inspection_items where condition='not_checked'),18::bigint,'new checklist has no invented findings');
select is((select readiness_result from inspections),'incomplete','new readiness is incomplete');
select is((select readiness_score from inspections),0,'new readiness score is zero');
select is((select criteria_version from inspections),'1.0','criteria version is persisted');
select is((select template_key from inspections),'mekareports_generic_readiness','state selection uses generic template');
select is(create_inspection(current_setting('test.job_a')::uuid,'pre_inspection','NY',current_setting('test.request')::uuid,current_setting('test.member_a')::uuid),current_setting('test.inspection_a')::uuid,'repeated create is idempotent');
select is((select count(*) from inspections),1::bigint,'retry does not duplicate inspection');
select throws_ok($$select create_inspection(current_setting('test.job_b')::uuid,'multipoint','',gen_random_uuid(),current_setting('test.member_a')::uuid)$$,'42501',null,'cross-shop create RPC denied');
select throws_ok($$select create_inspection(current_setting('test.job_a')::uuid,'multipoint','',gen_random_uuid(),current_setting('test.member_b')::uuid)$$,'22023',null,'cross-shop inspection technician denied');
select throws_ok($$update inspections set readiness_score=100,readiness_result='likely_ready'$$,'42501',null,'client cannot forge readiness');
select throws_ok($$update inspections set status='completed'$$,'42501',null,'client cannot bypass completion action');
select throws_ok($$update inspection_items set weight=0,required=false,critical=false$$,'42501',null,'client cannot forge criteria');
select throws_ok($$update inspection_items set condition='pass'$$,'23514',null,'unsupported condition rejected');
select set_config('test.item_a',(select id::text from inspection_items order by sort_order limit 1),true);
select lives_ok($$update inspection_items set condition='good',measurement='Verified test measurement'$$,'technician records findings');
select is((select readiness_score from inspections),100,'all good yields 100 percent');
select is((select readiness_result from inspections),'likely_ready','all good is likely ready');
select lives_ok($$update inspection_items set condition='urgent' where id=current_setting('test.item_a')::uuid$$,'critical urgent observation accepted');
select ok((select readiness_score>=85 from inspections),'critical blocker example retains high numeric score');
select is((select readiness_result from inspections),'high_risk','critical urgent overrides high score');
select is((select jsonb_array_length(readiness_blockers) from inspections),1,'critical blocker persisted');
select lives_ok($$update inspection_items set condition='not_checked' where id=current_setting('test.item_a')::uuid$$,'unchecked observation accepted');
select is((select readiness_result from inspections),'incomplete','required unchecked overrides numeric score');
select lives_ok($$update inspection_items set condition='attention'$$,'attention findings accepted');
select is((select readiness_score from inspections),50,'attention earns half weight');
select is((select readiness_result from inspections),'high_risk','score below 65 yields high risk');
select lives_ok($$update inspection_items set condition='good' where sort_order<9$$,'mixed findings accepted');
select ok((select readiness_score between 65 and 84 from inspections),'mixed result has middle score');
select is((select readiness_result from inspections),'needs_attention','middle score needs attention');
select throws_ok($$select save_inspection(current_setting('test.inspection_a')::uuid,'2000-01-01', '[]','',false,false)$$,'40001',null,'stale save cannot overwrite findings');
select lives_ok($$select save_inspection(i.id,i.updated_at,(select jsonb_agg(jsonb_build_object('id',id,'condition','good','weight',999,'required',false,'critical',false,'measurement','test','technician_note','test','recommendation','test')) from inspection_items),'Saved progress',false,false) from inspections i$$,'atomic save ignores forged definition fields');
select is((select readiness_score from inspections),100,'score recalculates from authoritative weights');
select is((select bool_and(required) from inspection_items),true,'required definitions retained');
select is((select status from inspections),'in_progress','save progress marks in progress');
select lives_ok($$update inspection_items set condition='not_checked' where id=current_setting('test.item_a')::uuid$$,'unchecked field persisted');
select throws_ok($$select save_inspection(i.id,i.updated_at,(select jsonb_agg(to_jsonb(t)) from inspection_items t),'Complete',true,false) from inspections i$$,'22023',null,'completion requires acknowledgement of unchecked items');
select is((select status from inspections),'in_progress','failed completion leaves prior state intact');
select lives_ok($$select save_inspection(i.id,i.updated_at,(select jsonb_agg(to_jsonb(t)) from inspection_items t),'Complete with limitation',true,true) from inspections i$$,'intentional incomplete completion allowed');
select is((select status from inspections),'completed','completion persists');
select ok((select completed_at is not null from inspections),'completion timestamp recorded');
select is((select readiness_result from inspections),'incomplete','completion does not invent good results');
select is((select status from work_orders),'open','inspection never completes or regresses work order');
select throws_ok($$update inspection_items set condition='good'$$,'22023',null,'completed checklist is immutable');
select set_config('test.multipoint',create_inspection(current_setting('test.job_a')::uuid,'multipoint','',gen_random_uuid(),current_setting('test.member_a')::uuid)::text,true);
select is((select count(*) from inspection_items where inspection_id=current_setting('test.multipoint')::uuid),22::bigint,'multi-point checklist snapshots twenty-two items');
select is((select readiness_score from inspections where id=current_setting('test.multipoint')::uuid),null::integer,'multipoint does not claim readiness score');
select throws_ok($$update inspection_items set inspection_id=current_setting('test.inspection_b')::uuid$$,'42501',null,'items cannot move across parents');
with changed as(update inspection_items set condition='urgent' where inspection_id=current_setting('test.inspection_b')::uuid returning id) select is((select count(*) from changed),0::bigint,'cross-shop item changes affect nothing');
select throws_ok($$select save_inspection(current_setting('test.inspection_b')::uuid,now(),'[]','forged',false,false)$$,'42501',null,'cross-shop save RPC denied');
select set_config('test.photo_id',gen_random_uuid()::text,true);
select set_config('test.photo_path',current_setting('test.shop_a') || '/' || current_setting('test.inspection_a') || '/' || current_setting('test.photo_id') || '.jpg',true);
select lives_ok($$insert into storage.objects(bucket_id,name,owner_id) values('inspection-photos',current_setting('test.photo_path'),current_setting('test.tech_a'))$$,'technician may upload object to own inspection');
select lives_ok($$insert into inspection_photos(id,shop_id,inspection_id,inspection_item_id,storage_path,caption) values(current_setting('test.photo_id')::uuid,current_setting('test.shop_a')::uuid,current_setting('test.inspection_a')::uuid,current_setting('test.item_a')::uuid,current_setting('test.photo_path'),'Temporary metadata fixture')$$,'photo metadata accepts own inspection/item');
select is((select count(*) from inspection_photos),1::bigint,'own photo metadata readable');
select is((select count(*) from storage.objects where bucket_id='inspection-photos'),1::bigint,'own object readable');
select throws_ok($$insert into inspection_photos(shop_id,inspection_id,inspection_item_id,storage_path) values(current_setting('test.shop_a')::uuid,current_setting('test.inspection_a')::uuid,current_setting('test.item_b')::uuid,'invalid')$$,null,null,'foreign item photo association rejected');
select throws_ok($$insert into storage.objects(bucket_id,name) values('inspection-photos',current_setting('test.shop_b') || '/' || current_setting('test.inspection_b') || '/' || gen_random_uuid() || '.jpg')$$,'42501',null,'cross-shop object upload denied');
select throws_ok($$insert into storage.objects(bucket_id,name) values('inspection-photos',current_setting('test.shop_a') || '/' || current_setting('test.inspection_b') || '/' || gen_random_uuid() || '.jpg')$$,'42501',null,'forged folder/inspection pairing denied');
select throws_ok($$insert into storage.objects(bucket_id,name) values('inspection-photos',current_setting('test.shop_a') || '/' || current_setting('test.inspection_a') || '/untrusted.svg')$$,'42501',null,'unsupported object path rejected');
select set_config('request.jwt.claim.sub',current_setting('test.owner_b'),true);
select is((select count(*) from diagnoses where shop_id=current_setting('test.shop_a')::uuid),0::bigint,'other shop cannot read diagnosis');
with changed as(update diagnoses set ai_summary='forged' where shop_id=current_setting('test.shop_a')::uuid returning id) select is((select count(*) from changed),0::bigint,'cross-shop diagnosis update denied');
select is((select count(*) from inspections where shop_id=current_setting('test.shop_a')::uuid),0::bigint,'other shop cannot read inspections');
select is((select count(*) from inspection_items where inspection_id=current_setting('test.inspection_a')::uuid),0::bigint,'items protected by parent shop');
select is((select count(*) from inspection_photos),0::bigint,'other shop cannot read photo metadata');
select is((select count(*) from storage.objects where bucket_id='inspection-photos'),0::bigint,'other shop cannot read photo object');
select throws_ok($$insert into inspection_photos(id,shop_id,inspection_id,storage_path) values(current_setting('test.photo_id')::uuid,current_setting('test.shop_a')::uuid,current_setting('test.inspection_a')::uuid,current_setting('test.photo_path'))$$,'42501',null,'other shop cannot create photo metadata');
select set_config('request.jwt.claim.sub','',true);
select set_config('request.jwt.claims','{}',true);
select is((select count(*) from diagnoses),0::bigint,'missing identity cannot read diagnoses');
select is((select count(*) from inspections),0::bigint,'missing identity cannot read inspections');
set local role anon;
select throws_ok($$select * from diagnoses$$,'42501',null,'anonymous diagnosis denied');
select throws_ok($$select * from inspections$$,'42501',null,'anonymous inspection denied');
select throws_ok($$select * from inspection_items$$,'42501',null,'anonymous findings denied');
select throws_ok($$select * from inspection_photos$$,'42501',null,'anonymous photo metadata denied');
select is((select count(*) from storage.objects where bucket_id='inspection-photos'),0::bigint,'anonymous objects denied');
select throws_ok($$select create_inspection(current_setting('test.job_a')::uuid,'multipoint','',gen_random_uuid(),current_setting('test.member_a')::uuid)$$,'42501',null,'anonymous inspection RPC denied');
reset role;
select is((select count(*) from auth.users where id in(current_setting('test.owner_a')::uuid,current_setting('test.owner_b')::uuid,current_setting('test.tech_a')::uuid)),3::bigint,'all test Auth accounts remain until rollback');
select * from finish();
rollback;
