begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select set_config('test.owner',gen_random_uuid()::text,true);
select set_config('test.other',gen_random_uuid()::text,true);
select set_config('test.tech',gen_random_uuid()::text,true);
insert into auth.users(id) values(current_setting('test.owner')::uuid),(current_setting('test.other')::uuid),(current_setting('test.tech')::uuid);
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
select set_config('test.shop',create_initial_shop('Phase 8 rollback fixture')::text,true);
insert into customers(shop_id,first_name,last_name) values(current_setting('test.shop')::uuid,'Document','Fixture');
select set_config('test.customer',(select id::text from customers),true);
insert into vehicles(shop_id,customer_id,mileage) values(current_setting('test.shop')::uuid,current_setting('test.customer')::uuid,10000);
select set_config('test.vehicle',(select id::text from vehicles),true);
insert into work_orders(shop_id,customer_id,vehicle_id,mileage_in,status,technician_notes) values(current_setting('test.shop')::uuid,current_setting('test.customer')::uuid,current_setting('test.vehicle')::uuid,10000,'open','SECRET_INTERNAL_PHASE8');
select set_config('test.job',(select id::text from work_orders),true);
select throws_ok($$select manage_document('repair_report',current_setting('test.job')::uuid,'create','{}')$$,'22023',null,'unfinished job cannot generate report');
select set_config('test.service',manage_repair(current_setting('test.job')::uuid,'service',jsonb_build_object('description','Completed repair','labor_hours','1.50','labor_rate','120','fees_amount','5','request_key',gen_random_uuid()))->>'id',true);
select manage_repair(current_setting('test.job')::uuid,'part',jsonb_build_object('service_id',current_setting('test.service'),'part_name','Fixture part','quantity','2','unit_price','45.55','unit_cost','13.37','request_key',gen_random_uuid()));
select manage_repair(current_setting('test.job')::uuid,'service',jsonb_build_object('description','Declined repair','labor_hours','1','labor_rate','60','sort_order',1,'request_key',gen_random_uuid()));
select set_config('test.rec',manage_repair(current_setting('test.job')::uuid,'recommend',jsonb_build_object('title','Future fixture','priority','medium','recommended_date',(current_date-1)::text,'recommended_mileage','10500','request_key',gen_random_uuid()))->>'id',true);
select set_config('test.estimate',manage_repair(current_setting('test.job')::uuid,'draft','{}')->>'id',true);
select manage_repair(current_setting('test.job')::uuid,'estimate_notes','{"internal_note":"SECRET_INTERNAL_PHASE8"}');
select manage_repair(current_setting('test.job')::uuid,'present','{}');
select record_staff_approval(current_setting('test.estimate')::uuid,'[{"line":1,"decision":"approved"},{"line":2,"decision":"declined"}]','Customer','',true,'phone');
select manage_repair(current_setting('test.job')::uuid,'start',jsonb_build_object('id',current_setting('test.service')));
select manage_repair(current_setting('test.job')::uuid,'complete_service',jsonb_build_object('id',current_setting('test.service'),'completion_note','Customer-safe completion note'));
select manage_repair(current_setting('test.job')::uuid,'complete_job','{"mileage_out":10010}');
select set_config('test.report',manage_document('repair_report',current_setting('test.job')::uuid,'create','{}')->>'id',true);
select is(manage_document('repair_report',current_setting('test.job')::uuid,'create','{}')->>'id',current_setting('test.report'),'report generation retry returns same draft');
select matches((select report_number from repair_reports),'^RPT-[0-9]{4}-[0-9]{6,}$','professional report number');
select throws_ok($$select create_document_link('repair_report',current_setting('test.report')::uuid)$$,'22023',null,'draft report cannot be shared');
select lives_ok($$select manage_document('repair_report',current_setting('test.report')::uuid,'finalize','{}')$$,'report finalized');
select ok((select report_snapshot::text like '%Customer-safe completion note%' from repair_reports),'performed work is snapshotted');
select ok((select report_snapshot::text not like '%SECRET_INTERNAL_PHASE8%' from repair_reports),'report excludes internal notes');
select ok((select report_snapshot::text not like '%13.37%' from repair_reports),'report excludes cost');
select ok((select bool_and(jsonb_typeof(section)='object') from repair_reports, lateral jsonb_array_elements(report_snapshot->'sections') section),'report sections are a flat customer document structure');
select throws_ok($$update repair_reports set report_snapshot='{}'$$,'42501',null,'staff cannot mutate final snapshot directly');
reset role;
select throws_ok($$update repair_reports set report_snapshot='{}' where id=current_setting('test.report')::uuid$$,'22023',null,'final snapshot also protected by trigger');
insert into shop_members(shop_id,user_id,role) values(current_setting('test.shop')::uuid,current_setting('test.tech')::uuid,'technician');
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
select set_config('test.invoice',manage_document('invoice',current_setting('test.job')::uuid,'create','{}')->>'id',true);
select is((select total from work_order_invoices),276.10::numeric,'invoice includes only completed authorized work, excluding declined repair');
select is((select labor_total from work_order_invoices),180::numeric,'invoice labor exact');
select is((select parts_total from work_order_invoices),91.10::numeric,'invoice parts exact');
select is((select tax_amount from work_order_invoices),0::numeric,'invoice pre-tax');
select is((select count(*) from work_order_receipts),0::bigint,'no receipt before payment');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','10','method','cash','request_key',gen_random_uuid()))$$,'22023',null,'draft invoice cannot receive payment');
select manage_document('invoice',current_setting('test.invoice')::uuid,'issue','{}');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','-1','method','cash','request_key',gen_random_uuid()))$$,'22023',null,'negative payment denied');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','0','method','cash','request_key',gen_random_uuid()))$$,'22023',null,'zero payment denied');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','300','method','cash','request_key',gen_random_uuid()))$$,'22023',null,'overpayment denied');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','10','method','card','payment_reference','4111111111111111','request_key',gen_random_uuid()))$$,'22023',null,'full card number rejected');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','10','method','card','payment_reference','CVV 123','request_key',gen_random_uuid()))$$,'23514',null,'credential-labelled reference rejected');
select set_config('test.retry',gen_random_uuid()::text,true);
select set_config('test.receipt',manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','100','method','cash','request_key',current_setting('test.retry')))->>'receipt_id',true);
select is((select status from work_order_invoices),'partially_paid','partial payment status');
select is((select balance_due from work_order_invoices),176.10::numeric,'partial balance exact');
select is(manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','100','method','cash','request_key',current_setting('test.retry')))->>'receipt_id',current_setting('test.receipt'),'payment retry returns same receipt');
select is((select count(*) from work_order_payments),1::bigint,'payment retry cannot double charge');
select matches((select receipt_number from work_order_receipts),'^RCT-[0-9]{4}-[0-9]{6,}$','receipt numbered independently');
select ok((select snapshot::text like '%176.10%' from work_order_receipts),'receipt retains balance at payment');
select manage_document('invoice',current_setting('test.invoice')::uuid,'payment',jsonb_build_object('amount','176.10','method','card','request_key',gen_random_uuid()));
select is((select status from work_order_invoices),'paid','final payment marks paid');
select is((select balance_due from work_order_invoices),0::numeric,'final balance zero');
select ok((select paid_at is not null from work_order_invoices),'payment time retained');
reset role;
select throws_ok($$insert into work_order_receipts(shop_id,work_order_id,invoice_id,payment_id,receipt_number,snapshot) values(current_setting('test.shop')::uuid,current_setting('test.job')::uuid,current_setting('test.invoice')::uuid,gen_random_uuid(),'RCT-NO-PAYMENT','{}')$$,'23503',null,'receipt foreign key requires a real payment in the same invoice context');
set local role authenticated;
select ok((select snapshot::text like '%176.10%' from work_order_receipts where id=current_setting('test.receipt')::uuid),'first receipt remains historical after final payment');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'void','{}')$$,'22023',null,'paid invoice cannot be voided');
select set_config('test.link',create_document_link('repair_report',current_setting('test.report')::uuid)::text,true);
select set_config('test.token',current_setting('test.link')::jsonb->>'token',true);
select set_config('test.receipt_token',create_document_link('receipt',current_setting('test.receipt')::uuid)->>'token',true);
select throws_ok($$select token_hash from customer_document_links$$,'42501',null,'token hashes excluded from ordinary projections');
select set_config('test.comm',prepare_communication('repair_report',current_setting('test.report')::uuid,'sms','+15555550123','Review your report',gen_random_uuid())::text,true);
select is(claim_communication((current_setting('test.comm')::jsonb->>'id')::uuid,current_setting('test.comm')::jsonb->>'token')->>'unconfigured','true','SMS accurately reports provider unavailable');
select is((select status from customer_communications),'draft','SMS remains draft');
select ok((select sent_at is null and delivered_at is null from customer_communications),'SMS never claims transmission or delivery');
select throws_ok($$update customer_communications set status='delivered'$$,'42501',null,'arbitrary status mutation denied');
select throws_ok($$select finish_communication((current_setting('test.comm')::jsonb->>'id')::uuid,gen_random_uuid(),true,'fake')$$,'22023',null,'draft SMS cannot be marked sent through transport completion');
select throws_ok($$select private.document_source('repair_report',current_setting('test.report')::uuid)$$,'42501',null,'unfiltered private source helper cannot be called by authenticated clients');
select is((select due_state from service_reminder_readiness),'overdue','past date overdue');
select manage_repair(current_setting('test.job')::uuid,'future',jsonb_build_object('id',current_setting('test.rec'),'recommended_date',current_date::text));
select is((select due_state from service_reminder_readiness),'due','today date due');
select manage_repair(current_setting('test.job')::uuid,'future',jsonb_build_object('id',current_setting('test.rec'),'recommended_date',(current_date+30)::text,'recommended_mileage','10500'));
select is((select due_state from service_reminder_readiness),'upcoming','future date and mileage upcoming');
select manage_repair(current_setting('test.job')::uuid,'future',jsonb_build_object('id',current_setting('test.rec'),'recommended_mileage','10000'));
select is((select due_state from service_reminder_readiness),'due','known mileage at target due');
update vehicles set mileage=null where id=current_setting('test.vehicle')::uuid;
select is((select due_state from service_reminder_readiness),'unknown','unknown mileage never falsely overdue');
select is((select mileage_state from service_reminder_readiness),'unknown','unknown mileage explicit');
select set_config('request.jwt.claim.sub',current_setting('test.tech'),true);
select is((select count(*) from repair_reports),1::bigint,'technician reads necessary repair report');
select is((select count(*) from work_order_invoices),0::bigint,'technician cannot read financial documents');
select is((select count(*) from customer_communications),0::bigint,'technician cannot read customer communications');
select throws_ok($$select manage_document('invoice',current_setting('test.invoice')::uuid,'issue','{}')$$,'42501',null,'technician cannot manage invoices');
select set_config('request.jwt.claim.sub',current_setting('test.other'),true);
select create_initial_shop('Phase 8 other rollback shop');
select is((select count(*) from work_order_invoices),0::bigint,'cross-shop invoices denied');
select is((select count(*) from work_order_payments),0::bigint,'cross-shop payments denied');
select is((select count(*) from work_order_receipts),0::bigint,'cross-shop receipts denied');
select is((select count(*) from customer_document_links),0::bigint,'cross-shop link metadata denied');
select is((select count(*) from customer_communications),0::bigint,'cross-shop communications denied');
select throws_ok($$select create_document_link('repair_report',current_setting('test.report')::uuid)$$,'42501',null,'cross-shop sharing denied');
set local role anon;
select set_config('request.jwt.claim.sub','',true);
select throws_ok($$select * from work_order_invoices$$,'42501',null,'anonymous invoices denied');
select throws_ok($$select * from work_order_payments$$,'42501',null,'anonymous payments denied');
select throws_ok($$select * from work_order_receipts$$,'42501',null,'anonymous receipts denied');
select throws_ok($$select * from customer_communications$$,'42501',null,'anonymous communications denied');
select throws_ok($$select * from customer_document_links$$,'42501',null,'anonymous links denied');
select throws_ok($$select finish_communication(gen_random_uuid(),gen_random_uuid(),true,'fake')$$,'42501',null,'anonymous cannot falsify transport result');
select is(read_customer_document('invalid'),null::jsonb,'invalid token denied');
select is(read_customer_document(repeat('0',64)),null::jsonb,'unknown token denied');
select is(read_customer_document(current_setting('test.token'))->>'kind','repair_report','anonymous report token works');
select is(read_customer_document(current_setting('test.receipt_token'))->>'kind','receipt','receipt token is bound to receipt');
select ok(read_customer_document(current_setting('test.token'))::text not like '%'||current_setting('test.job')||'%','no database ID in public report');
select ok(read_customer_document(current_setting('test.token'))::text not like '%unit_cost%','no cost field in public document');
select ok(read_customer_document(current_setting('test.token'))::text not like '%SECRET_INTERNAL_PHASE8%','no internal note in public document');
reset role;
update customer_document_links set expires_at=now()-interval '1 second' where id=(current_setting('test.link')::jsonb->>'id')::uuid;
set local role anon;
select is(read_customer_document(current_setting('test.token')),null::jsonb,'expired token denied');
set local role authenticated;
select set_config('request.jwt.claim.sub',current_setting('test.owner'),true);
select set_config('test.link',create_document_link('repair_report',current_setting('test.report')::uuid)::text,true);
select revoke_document_link((current_setting('test.link')::jsonb->>'id')::uuid);
select is(read_customer_document(current_setting('test.link')::jsonb->>'token'),null::jsonb,'revoked token denied');
select * from finish();
rollback;
