-- All fixtures and mutations roll back. Run: npx.cmd supabase test db --local
begin;
set local search_path = public, extensions;
select no_plan();
select set_config('test.owner_a', gen_random_uuid()::text, true);
select set_config('test.owner_b', gen_random_uuid()::text, true);
select set_config('test.tech_a', gen_random_uuid()::text, true);
select set_config('test.tech_b', gen_random_uuid()::text, true);
insert into auth.users(id) values (current_setting('test.owner_a')::uuid), (current_setting('test.owner_b')::uuid), (current_setting('test.tech_a')::uuid), (current_setting('test.tech_b')::uuid);
set local role authenticated;
select set_config('request.jwt.claim.sub', current_setting('test.owner_a'), true);
select set_config('test.shop_a', create_initial_shop('Phase 5 test A')::text, true);
insert into customers(shop_id, first_name, last_name) values (current_setting('test.shop_a')::uuid, 'Job', 'A');
select set_config('test.customer_a', (select id::text from customers), true);
insert into vehicles(shop_id, customer_id, make) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, 'Test A');
select set_config('test.vehicle_a', (select id::text from vehicles), true);
select set_config('request.jwt.claim.sub', current_setting('test.owner_b'), true);
select set_config('test.shop_b', create_initial_shop('Phase 5 test B')::text, true);
insert into customers(shop_id, first_name, last_name) values (current_setting('test.shop_b')::uuid, 'Job', 'B');
select set_config('test.customer_b', (select id::text from customers), true);
insert into vehicles(shop_id, customer_id, make) values (current_setting('test.shop_b')::uuid, current_setting('test.customer_b')::uuid, 'Test B');
select set_config('test.vehicle_b', (select id::text from vehicles), true);
insert into appointments(shop_id, customer_id, vehicle_id, scheduled_start, status) values (current_setting('test.shop_b')::uuid, current_setting('test.customer_b')::uuid, current_setting('test.vehicle_b')::uuid, now(), 'confirmed');
insert into work_orders(shop_id, customer_id, vehicle_id, status) values (current_setting('test.shop_b')::uuid, current_setting('test.customer_b')::uuid, current_setting('test.vehicle_b')::uuid, 'open');
reset role;
insert into shop_members(shop_id, user_id, role) values (current_setting('test.shop_a')::uuid, current_setting('test.tech_a')::uuid, 'technician'), (current_setting('test.shop_b')::uuid, current_setting('test.tech_b')::uuid, 'technician');
select set_config('test.member_a', (select id::text from shop_members where user_id = current_setting('test.tech_a')::uuid), true);
select set_config('test.member_b', (select id::text from shop_members where user_id = current_setting('test.tech_b')::uuid), true);
set local role authenticated;
select set_config('request.jwt.claim.sub', current_setting('test.owner_a'), true);

select lives_ok($$insert into appointments(shop_id, customer_id, scheduled_start, status, customer_concern) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, now(), 'confirmed', 'Rough idle')$$, 'owner creates appointment without initial vehicle');
select set_config('test.appointment_a', (select id::text from appointments), true);
select is((select count(*) from appointments), 1::bigint, 'reads own appointment only');
select is((select count(*) from appointment_listing), 1::bigint, 'invoker appointment view preserves isolation');
select is((select count(*) from work_orders), 0::bigint, 'other shop work order invisible');
select is((select count(*) from work_order_listing), 0::bigint, 'invoker work order view preserves isolation');
select is((select count(*) from list_shop_technicians(current_setting('test.shop_a')::uuid)), 1::bigint, 'directory lists own shop technician');
select is((select count(*) from list_shop_technicians(current_setting('test.shop_b')::uuid)), 0::bigint, 'directory hides other shop technicians');
select throws_ok($$insert into appointments(shop_id, customer_id, scheduled_start, status) values (current_setting('test.shop_b')::uuid, current_setting('test.customer_b')::uuid, now(), 'confirmed')$$, '42501', null, 'cross-shop appointment insertion denied');
select throws_ok($$insert into appointments(shop_id, customer_id, vehicle_id, scheduled_start, status) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, current_setting('test.vehicle_b')::uuid, now(), 'confirmed')$$, '23503', null, 'cross-shop vehicle appointment denied');
select throws_ok($$update appointments set shop_id = current_setting('test.shop_b')::uuid$$, '42501', null, 'appointment tenancy immutable');
select throws_ok($$update appointments set customer_id = current_setting('test.customer_b')::uuid$$, '42501', null, 'appointment customer immutable');
select throws_ok($$update appointments set scheduled_end = scheduled_start - interval '1 hour'$$, '23514', null, 'end before start rejected');
select lives_ok($$update appointments set internal_notes = 'Check in at front desk'$$, 'appointment edits allowed');
select lives_ok($$update appointments set status = 'checked_in'$$, 'check in allowed');
select is((select status from appointments), 'checked_in', 'check in persists');
select is((select customer_concern from appointments), 'Rough idle', 'check in preserves concern');
select throws_ok($$update appointments set status = 'requested'$$, '22023', null, 'invalid appointment transition denied');

select throws_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, status) values (current_setting('test.shop_b')::uuid, current_setting('test.customer_b')::uuid, current_setting('test.vehicle_b')::uuid, 'open')$$, '42501', null, 'cross-shop work order insertion denied');
select throws_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, status, assigned_technician_id) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, current_setting('test.vehicle_a')::uuid, 'open', current_setting('test.member_b')::uuid)$$, '22023', null, 'cross-shop technician denied');
select lives_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, appointment_id, status, customer_complaint, assigned_technician_id) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, current_setting('test.vehicle_a')::uuid, current_setting('test.appointment_a')::uuid, 'open', 'Rough idle', current_setting('test.member_a')::uuid)$$, 'create job from appointment');
select set_config('test.work_order_a', (select id::text from work_orders), true);
select matches((select work_order_number from work_orders), '^WO-[0-9]{4}-[0-9]{6,}$', 'professional work order number assigned');
select is((select status from appointments), 'in_service', 'job starts appointment service atomically');
select is((select vehicle_id from appointments), current_setting('test.vehicle_a')::uuid, 'vehicle is linked to vehicle-less appointment');
select is((select count(*) from work_order_listing), 1::bigint, 'reads own job through invoker view');
select throws_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, appointment_id, status) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, current_setting('test.vehicle_a')::uuid, current_setting('test.appointment_a')::uuid, 'open')$$, '23505', null, 'duplicate job from appointment denied');
select is((select count(*) from work_orders), 1::bigint, 'duplicate leaves exactly one job');
select throws_ok($$update appointments set status = 'cancelled'$$, '22023', null, 'linked appointment status managed by job');
select throws_ok($$update appointments set vehicle_id = null$$, '22023', null, 'linked appointment vehicle immutable');
select throws_ok($$update work_orders set work_order_number = 'FORGED'$$, '42501', null, 'client cannot change job number');
select throws_ok($$update work_orders set shop_id = current_setting('test.shop_b')::uuid$$, '42501', null, 'job tenancy immutable');
select throws_ok($$update work_orders set vehicle_id = current_setting('test.vehicle_b')::uuid$$, '42501', null, 'job vehicle immutable');
select throws_ok($$update work_orders set status = 'completed'$$, '22023', null, 'cannot skip workflow stages');
select lives_ok($$update work_orders set status = 'diagnosing'$$, 'open to diagnosing');
select lives_ok($$update work_orders set status = 'waiting_approval'$$, 'diagnosing to waiting approval');
select lives_ok($$update work_orders set status = 'approved'$$, 'waiting approval to approved');
select lives_ok($$update work_orders set status = 'in_progress'$$, 'approved to in progress');
select lives_ok($$update work_orders set status = 'completed'$$, 'in progress to completed');
select is((select status from appointments), 'completed', 'completion synchronizes appointment');
select ok((select completed_at is not null from work_orders), 'completion timestamp populated');
select throws_ok($$update work_orders set status = 'open'$$, '22023', null, 'completed is terminal');
select throws_ok($$delete from appointments$$, '42501', null, 'appointment deletion disabled');
select throws_ok($$delete from work_orders$$, '42501', null, 'work order deletion disabled');

-- Same shop, different customer: the composite FK must enforce ownership too.
insert into customers(shop_id, first_name, last_name) values (current_setting('test.shop_a')::uuid, 'Other', 'Customer');
select set_config('test.other_customer', (select id::text from customers where first_name = 'Other'), true);
select throws_ok($$insert into appointments(shop_id, customer_id, vehicle_id, scheduled_start, status) values (current_setting('test.shop_a')::uuid, current_setting('test.other_customer')::uuid, current_setting('test.vehicle_a')::uuid, now(), 'confirmed')$$, '23503', null, 'same-shop wrong customer vehicle rejected for appointment');
select throws_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, status) values (current_setting('test.shop_a')::uuid, current_setting('test.other_customer')::uuid, current_setting('test.vehicle_a')::uuid, 'open')$$, '23503', null, 'same-shop wrong customer vehicle rejected for job');
select lives_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, status) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, current_setting('test.vehicle_a')::uuid, 'draft')$$, 'walk-in draft can be created');
select is((select count(distinct work_order_number) from work_orders), 2::bigint, 'numbers unique per shop');
select lives_ok($$update work_orders set status = 'cancelled' where status = 'draft'$$, 'draft cancellation allowed');

select set_config('request.jwt.claim.sub', current_setting('test.tech_a'), true);
select is((select count(*) from appointments), 1::bigint, 'technician reads own shop appointments');
select is((select count(*) from work_orders), 2::bigint, 'technician reads own shop jobs');
select throws_ok($$insert into appointments(shop_id, customer_id, scheduled_start, status) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, now(), 'confirmed')$$, '42501', null, 'technician cannot create appointment');
select throws_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, status) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, current_setting('test.vehicle_a')::uuid, 'open')$$, '42501', null, 'technician cannot create job');
with changed as (update appointments set internal_notes = 'denied' returning id) select is((select count(*) from changed), 0::bigint, 'technician appointment update denied');
with changed as (update work_orders set technician_notes = 'denied' returning id) select is((select count(*) from changed), 0::bigint, 'technician job update denied');
select set_config('request.jwt.claims', json_build_object('sub', current_setting('test.tech_a'), 'user_metadata', json_build_object('role', 'owner'))::text, true);
select throws_ok($$insert into work_orders(shop_id, customer_id, vehicle_id, status) values (current_setting('test.shop_a')::uuid, current_setting('test.customer_a')::uuid, current_setting('test.vehicle_a')::uuid, 'open')$$, '42501', null, 'editable metadata cannot authorize writes');

select set_config('request.jwt.claim.sub', current_setting('test.owner_b'), true);
select is((select count(*) from appointments where shop_id = current_setting('test.shop_a')::uuid), 0::bigint, 'reverse appointment isolation');
select is((select count(*) from work_orders where shop_id = current_setting('test.shop_a')::uuid), 0::bigint, 'reverse job isolation');
with changed as (update appointments set internal_notes = 'denied' where shop_id = current_setting('test.shop_a')::uuid returning id) select is((select count(*) from changed), 0::bigint, 'cross-shop appointment update denied');
with changed as (update work_orders set technician_notes = 'denied' where shop_id = current_setting('test.shop_a')::uuid returning id) select is((select count(*) from changed), 0::bigint, 'cross-shop job update denied');

reset role;
update shop_members set role = 'manager' where user_id = current_setting('test.owner_b')::uuid;
set local role authenticated;
select lives_ok($$update appointments set internal_notes = 'manager'$$, 'manager edits appointments');
select lives_ok($$update work_orders set technician_notes = 'manager'$$, 'manager edits work orders');
select is((select technician_notes from work_orders), 'manager', 'manager update persists');
reset role;
update shop_members set role = 'service_advisor' where user_id = current_setting('test.owner_b')::uuid;
set local role authenticated;
select lives_ok($$update appointments set internal_notes = 'advisor'$$, 'advisor edits appointments');
select lives_ok($$update work_orders set technician_notes = 'advisor'$$, 'advisor edits jobs');
select is((select internal_notes from appointments), 'advisor', 'advisor update persists');

-- Insert-only IDs let a browser retry the same creation without duplicate jobs.
select set_config('test.retry_appt',gen_random_uuid()::text,true);
select lives_ok($$insert into appointments(id,shop_id,customer_id,vehicle_id,scheduled_start,status) values(current_setting('test.retry_appt')::uuid,current_setting('test.shop_b')::uuid,current_setting('test.customer_b')::uuid,current_setting('test.vehicle_b')::uuid,now(),'confirmed')$$,'advisor can supply a stable appointment retry ID');
select throws_ok($$insert into appointments(id,shop_id,customer_id,vehicle_id,scheduled_start,status) values(current_setting('test.retry_appt')::uuid,current_setting('test.shop_b')::uuid,current_setting('test.customer_b')::uuid,current_setting('test.vehicle_b')::uuid,now(),'confirmed')$$,'23505',null,'appointment creation retry cannot duplicate');
select set_config('test.retry_job',gen_random_uuid()::text,true);
select lives_ok($$insert into work_orders(id,shop_id,customer_id,vehicle_id,status) values(current_setting('test.retry_job')::uuid,current_setting('test.shop_b')::uuid,current_setting('test.customer_b')::uuid,current_setting('test.vehicle_b')::uuid,'open')$$,'advisor can supply stable work-order retry ID');
select throws_ok($$insert into work_orders(id,shop_id,customer_id,vehicle_id,status) values(current_setting('test.retry_job')::uuid,current_setting('test.shop_b')::uuid,current_setting('test.customer_b')::uuid,current_setting('test.vehicle_b')::uuid,'open')$$,'23505',null,'work-order creation retry cannot duplicate');
select throws_ok($$update work_orders set id=gen_random_uuid()$$,'42501',null,'work-order IDs remain immutable');
select throws_ok($$update appointments set id=gen_random_uuid()$$,'42501',null,'appointment IDs remain immutable');

select set_config('request.jwt.claim.sub', '', true);
select set_config('request.jwt.claims', '{}', true);
select is((select count(*) from appointments), 0::bigint, 'missing identity sees no appointments');
select is((select count(*) from work_orders), 0::bigint, 'missing identity sees no jobs');
set local role anon;
select throws_ok($$select * from appointments$$, '42501', null, 'anonymous appointments denied');
select throws_ok($$select * from work_orders$$, '42501', null, 'anonymous jobs denied');
select throws_ok($$select * from appointment_listing$$, '42501', null, 'anonymous appointment view denied');
select throws_ok($$select * from work_order_listing$$, '42501', null, 'anonymous job view denied');
select throws_ok($$select * from list_shop_technicians(current_setting('test.shop_a')::uuid)$$, '42501', null, 'anonymous technician directory denied');
reset role;
delete from auth.users where id = current_setting('test.tech_a')::uuid;
select is((select assigned_technician_id from work_orders where id = current_setting('test.work_order_a')::uuid), null::uuid, 'deleting technician preserves job and clears assignment');
select * from finish();
rollback;
