project_id = "mekareports"

[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54330
major_version = 17

[studio]
enabled = true
port = 54333

[inbucket]
enabled = true
port = 54334
smtp_port = 54335
pop3_port = 54336

[analytics]
enabled = false
port = 54337
vector_port = 54338

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://localhost:3001",
  "http://localhost:3002"
]