import Link from "next/link";
import { z } from "zod";
import { requireShopContext } from "@/lib/auth/session";
import { workshopDb } from "@/lib/workshop/data";
import { canManageRecords } from "@/lib/workshop/permissions";
import { PageHeader } from "@/components/page-header";
import { panel,secondaryLink } from "@/components/workshop/record-ui";
import { moneyText } from "@/lib/repairs/validation";
import { SendDocumentLink } from "./shop-documents";
export default async function RemindersPage({searchParams}:{searchParams:Promise<{due?:string;priority?:string;customer?:string;vehicle?:string;status?:string}>}){
 const c=await requireShopContext();const q=await searchParams;const db=await workshopDb();let request=db.from("service_reminder_readiness").select("*").eq("shop_id",c.shop.id).order("recommended_date",{nullsFirst:false}).order("id").limit(50);
 const status=["recommended","scheduled","completed","declined","dismissed"].includes(q.status||"")?q.status!:q.status==="all"?"all":"recommended";if(status!=="all")request=request.eq("status",status);
 if(q.due==="due")request=request.in("due_state",["due","overdue"]);else if(["upcoming","overdue","unknown"].includes(q.due||""))request=request.eq("due_state",q.due!);
 if(["low","medium","high","urgent"].includes(q.priority||""))request=request.eq("priority",q.priority!);
 if(z.uuid().safeParse(q.customer).success)request=request.eq("customer_id",q.customer!);if(z.uuid().safeParse(q.vehicle).success)request=request.eq("vehicle_id",q.vehicle!);
 const [reminders,customers,vehicles]=await Promise.all([request,db.from("customers").select("id,first_name,last_name").eq("shop_id",c.shop.id).order("last_name").limit(500),db.from("vehicles").select("id,year,make,model,vin").eq("shop_id",c.shop.id).order("make").limit(500)]);if(reminders.error||customers.error||vehicles.error)throw new Error("Reminders temporarily unavailable.");
 const selectClass="mt-2 min-h-12 w-full rounded-xl border bg-white p-3";
 return <div className="space-y-6"><PageHeader eyebrow={c.shop.name} title="Service Reminders" description="Review future recommendations and manually prepare a customer reminder. No automatic messages are sent."/><form className="grid gap-3 sm:grid-cols-3"><label>Readiness<select className={selectClass} name="due" defaultValue={q.due||""}><option value="">All</option><option value="due">Due / overdue</option><option value="upcoming">Upcoming</option><option value="unknown">Unknown</option></select></label><label>Priority<select className={selectClass} name="priority" defaultValue={q.priority||""}><option value="">All</option>{["low","medium","high","urgent"].map(s=><option key={s}>{s}</option>)}</select></label><label>Status<select className={selectClass} name="status" defaultValue={status}><option value="all">All</option>{["recommended","scheduled","completed","declined","dismissed"].map(s=><option key={s}>{s}</option>)}</select></label><label>Customer<select className={selectClass} name="customer" defaultValue={q.customer||""}><option value="">All customers</option>{customers.data.map(r=><option key={r.id} value={r.id}>{r.first_name} {r.last_name}</option>)}</select></label><label>Vehicle<select className={selectClass} name="vehicle" defaultValue={q.vehicle||""}><option value="">All vehicles</option>{vehicles.data.map(r=><option key={r.id} value={r.id}>{r.year} {r.make} {r.model} · {r.vin}</option>)}</select></label><button className={`${secondaryLink} self-end min-h-12`}>Filter Reminders</button></form>
 <p className="text-sm text-slate-500">Date readiness uses the database&apos;s current date (UTC). Mileage uses the latest recorded vehicle mileage; unknown mileage is never treated as overdue. Showing up to 50 matching recommendations.</p>
 {reminders.data.map(r=><article key={r.id} className={`${panel} space-y-3`}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-bold">{r.title}</h2><span className="rounded-full bg-amber-50 px-4 py-2 font-bold capitalize">{r.due_state}</span></div><p>{r.customer_name} · {r.vehicle_name}</p><p className="whitespace-pre-wrap text-sm">{r.description}</p><p className="text-sm capitalize">{r.priority} priority · {r.status}</p><p className="text-sm">Date: {r.recommended_date||"Not set"} · {r.date_state?.replaceAll("_"," ")}</p><p className="text-sm">Target mileage: {r.recommended_mileage?.toLocaleString()??"Not set"} · Known mileage: {r.known_mileage?.toLocaleString()??"Unknown"} · {r.mileage_state?.replaceAll("_"," ")}</p>{r.estimated_cost!==null?<p>Estimated {moneyText(r.estimated_cost)} pre-tax</p>:null}<div className="flex flex-wrap gap-3">{r.work_order_id?<Link className={secondaryLink} href={`/work-orders/${r.work_order_id}`}>Work Order</Link>:null}{canManageRecords(c.role)&&r.status==="recommended"&&r.id?<SendDocumentLink kind="service_reminder" id={r.id} label="Send Reminder"/>:null}</div></article>)}{!reminders.data.length?<p className={panel}>No recommendations match these filters.</p>:null}</div>;
}
